// Generated by CoffeeScript 1.3.3
(function() {
  var expanda, init;

  $(function() {
    return init();
  });

  expanda = function(item) {
    return console.log('pew');
  };

  init = function(x) {
    var _this = this;
    console.log('ineeeet');
    return $('#rombs .romb').each(function(i, element) {
      $(element).click(function() {
        $(element).css({
          'z-index': -1,
          'background-color': '#666'
        });
        return $(element).animate({
          rotate: '0deg',
          width: '60px',
          height: '60px',
          marginLeft: '+=2px',
          marginTop: '+=2px'
        }, 500);
      });
      return $(element).animate({
        rotate: '45deg'
      }, 1);
    });
  };

}).call(this);
